### ISSUE TITLE
Get children of XMLElement

### ISSUE THREAD

**Issue by mollywoodnini** [SJTBA/Scrape#4]
Hi,

how can I get all children of an XMLElement to iterate over them?

Thanks in advance.

Cheers,
Nini

**Comment by broadwaylamb** [comment]
@mollywoodnini hi!

You can use the following code:

``` swift
let result = element.search(byXPath: "child::*")
```

And since the `result` is of type `XPathResult` that conforms to the `Collection` protocol, you can interate through it.
